#services:
#  db:
#    image: mysql
#    ports:
#      - 3308:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#  phpmyadmin:
#    image: phpmyadmin
#    ports:
#      - 9001:80
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: password
#  backend:
#    image: cxttonn/se331-backend:latest
#    ports:
#      - 8999:8080
#    environment:
#      - JAVA_PROFILE=prod,db
#    depends_on:
#      - db
#    restart: on-failure